// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDePaeLtMSkobbaHajzJBM69DQ6aANbDms',
    appId: '1:725664611084:web:1e3088c5300d970d776729',
    messagingSenderId: '725664611084',
    projectId: 'sapaalumni-559d6',
    authDomain: 'sapaalumni-559d6.firebaseapp.com',
    storageBucket: 'sapaalumni-559d6.firebasestorage.app',
    measurementId: 'G-FQJMT93NCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOf2Y0J7m2PUm0IYDhT2W5BtBpC6g9EJk',
    appId: '1:725664611084:android:7194b29e26146c61776729',
    messagingSenderId: '725664611084',
    projectId: 'sapaalumni-559d6',
    storageBucket: 'sapaalumni-559d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPWC-jm1LBzlG-8P5e85LqeuAAQRT8qz0',
    appId: '1:725664611084:ios:7374e7567f421d2c776729',
    messagingSenderId: '725664611084',
    projectId: 'sapaalumni-559d6',
    storageBucket: 'sapaalumni-559d6.firebasestorage.app',
    iosBundleId: 'com.example.sapaalumni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPWC-jm1LBzlG-8P5e85LqeuAAQRT8qz0',
    appId: '1:725664611084:ios:7374e7567f421d2c776729',
    messagingSenderId: '725664611084',
    projectId: 'sapaalumni-559d6',
    storageBucket: 'sapaalumni-559d6.firebasestorage.app',
    iosBundleId: 'com.example.sapaalumni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDePaeLtMSkobbaHajzJBM69DQ6aANbDms',
    appId: '1:725664611084:web:2edbff8b6afdfe79776729',
    messagingSenderId: '725664611084',
    projectId: 'sapaalumni-559d6',
    authDomain: 'sapaalumni-559d6.firebaseapp.com',
    storageBucket: 'sapaalumni-559d6.firebasestorage.app',
    measurementId: 'G-DM4CTR0G07',
  );
}
